version: '3'

services:
  bind9:
    container_name: dns_shifthunter
    image: ubuntu/bind9:latest
    hostname: zoo1
    environment:
      - BIND9_USER=root
      - TZ=Europe/Zurich
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped  
    
